<?php 
// Map SAML attributes to fields to appear on the user account page
function ucb_saml_mapping_simplesamlphp_auth_user_attributes(\Drupal\user\UserInterface $account, $attributes) {
  $saml_identikey = $attributes['urn:oid:0.9.2342.19200300.100.1.1'][0];
  $saml_role = $attributes['urn:oid:1.3.6.1.4.1.5923.1.1.1.1']; // affiliations
  $saml_email = $attributes['urn:oid:0.9.2342.19200300.100.1.3'][0];
  $flag = false;
  if($saml_identikey){
    $account->set('field_identikey', $saml_identikey);
    $flag = true;
  }
  if($saml_role) {
    $affiliations = '';
    foreach($saml_role as $i){
        $affiliations = $i . ", " . $affiliations;
    }
    $account->set('field_affiliations', $affiliations);
    $flag = true;
  }
  if($saml_email){
    $account->set('field_saml_email', $saml_email); // only for display purposes
    $flag = true;
  }
  return $flag ? $account : false;
}